apiVersion: v1
kind: Service
metadata:
  name: studybuddy-backend
  namespace: studybuddy
spec:
  selector:
    app: studybuddy-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
