apiVersion: v1
kind: Service
metadata:
  name: studybuddy-frontend
  namespace: studybuddy
spec:
  selector:
    app: studybuddy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
